### ISSUE TITLE
react 18 support

### ISSUE THREAD

**Issue by tobiaszuercher** [MrWolfZ/simplux#23]
any plans/schedule to support react 18?

currently i see warnings when using with react 18 cause of unmet dependencies. probably it just works with bumping those. i can try and create PR if you want.

`warning " > @simplux/react@0.17.0" has incorrect peer dependency "react@^16.14.0".`
`warning " > @simplux/react@0.17.0" has incorrect peer dependency "react-dom@^16.14.0".`

**Comment by MrWolfZ** [comment]
I just released version `0.18.0` which is compatible with React 18.
